### ISSUE TITLE
GPU info

### ISSUE THREAD

**Issue by medowz** [brunoandradebr/nzxt#1]
How do I get it to read my actual GPU card instead of intel's integrated GPU?

**Comment by brunoandradebr** [comment]
Can you please send me a photo to see how it's showing ? I'm working on a update then I fix it. I do not have integrated so I didn't realise this =)

**Comment by medowz** [comment]
Sure. Here you go. 
![IMG_0239](https://github.com/brunoandradebr/nzxt/assets/42414353/fdabe256-0ef3-44fd-af84-1580068b4c18)

**Comment by brunoandradebr** [comment]
thanks, I will be sending new version soon.

**Comment by brunoandradebr** [comment]
@medowz I've updated, please tell me if it's working properly. web integrations has a cache, to see the new panel, just add this to my url : https://brunoandradebr.github.io/nzxt/?cache=1

**Comment by brunoandradebr** [comment]
@medowz I've updated, please tell me if it's working properly

**Comment by medowz** [comment]
It's working flawlessly for me. Thank you for the update. 

![IMG_0253](https://github.com/brunoandradebr/nzxt/assets/42414353/eba6f04f-7646-4030-9449-02248b2faf81)

**Comment by brunoandradebr** [comment]
nice!! this fix has broken for another user so I come up with a more
universal solution. Could you please tell me if it's still working and
sorry for theme reset... I will work on a better update process. To check
if it was updated, check if beside DUAL INFO name has a v1.0.2

**Comment by medowz** [comment]
Current version is 1.0.3

<img width="132" alt="Screenshot 2023-09-14 033404" src="https://github.com/brunoandradebr/nzxt/assets/42414353/7b5e645d-7ff8-416c-87e0-b91964e562c6">

Still working great. Glad it worked out for the other user too after all.
Yes, the theme did reset indeed, but no worries man. 

Again, thank you.
