### ISSUE TITLE
[Improvement] Hide only the CPU & GPU name but let the logos

### ISSUE THREAD

**Issue by SimonR-Nano** [brunoandradebr/nzxt#10]
Hey,

For now, I don't have the time to edit your code to make this little improvement, but if you can, it will be really cool if we can hide the CPU & the GPU name but let the logos
Or, write "CPU" & "GPU" instead the current model :)

Thanks for your preset, I like it (I just bought the NZXT kraken elite rgb 360!

**Comment by brunoandradebr** [comment]
Thanks dude! I'll be considering this improvement.

**Comment by brunoandradebr** [comment]
Hey, @Naografix sorry for delay, was too busy las weeks =) but I've implemented your request, now you can edit cpu and gpu label color and alpha (misc > cpu/gpu label). If you wanna hide just set alpha to zero.  just click refresh button in nzxt interface to force update if dosen't get it automatic.

https://github.com/brunoandradebr/nzxt/commit/1161e13edc63e61e08de9cbc9e1cee7857a7e5f8
