### ISSUE TITLE
GIF less fluid/smooth

### ISSUE THREAD

**Issue by JulienMrgrd** [brunoandradebr/nzxt#12]
Hi Bruno!

First of all, congrats for this Kraken web integration, it's impressive and I'm already using it ;)

One thing you may have already noticed, it's that we can see a difference between the native GIF option in NZXT CAM vs your usage, in terms of fluidity. The GIF seems slow/jerky.

Any idea or solution ? (I'm not a React expert, I can't be really helpfull)

**Comment by JulienMrgrd** [comment]
Two smalls videos where you can see the differences : 
https://github.com/brunoandradebr/nzxt/assets/11616517/3d2fb55b-b80d-46f3-8426-b070de01b0be


https://github.com/brunoandradebr/nzxt/assets/11616517/c035dae9-abe5-48b1-8329-1d351e43fcce

**Comment by JulienMrgrd** [comment]
Two smalls videos where you can see the differences : 

https://github.com/brunoandradebr/nzxt/assets/11616517/84393f99-45cb-4cb4-99ce-f6ddb351f44f

https://github.com/brunoandradebr/nzxt/assets/11616517/e9a347e8-cdb4-45db-8f1a-8f46fb3c39ea

**Comment by brunoandradebr** [comment]
Hi, Julien. thanks! I really appreciate it. What kraken is yours ? It's a limitation to web integration, depending on what model you're using its maximum frame rate are limited. Before they presented me with the new kraken elite, I used Kraken Z63, If i'm not mistaken it was max 10 fps =(. When you're runing native gif its not running on a web browser view (like web integration do) and so, has no fps limitation. kraken elite runs max 40 fps its smooth, its so sad they won't update old ones. Have you checked your current frame rate ?

I have asked them about fps here: https://github.com/NZXTCorp/web-integrations-docs/issues/8

![image](https://github.com/brunoandradebr/nzxt/assets/4542059/59063b04-dd76-436f-9472-ed45517bfd58)

![image](https://github.com/brunoandradebr/nzxt/assets/4542059/b4e0f7de-71e0-418d-93b2-ed18bcaaeb66)
