### ISSUE TITLE
AMD GPU'S

### ISSUE THREAD

**Issue by V333Y** [brunoandradebr/nzxt#13]
would it be possible to remove manufacturer name and leave only model with amd gpu's?
It causes there to be 2 lines of text on the gpu label leaving everything misaligned unlike the nvidia one.

AMD example:
![image_123927839](https://github.com/brunoandradebr/nzxt/assets/173413820/bf8f25e9-d659-42df-a7de-5f6e6ebddb05)

NVIDIA example:
![print2](https://github.com/brunoandradebr/nzxt/assets/173413820/118fc693-fd99-461e-bcf0-175e50a539e5)

note how it says AMD Radeon RX 7900XTX instead of RX 7900XTX or even just 7900XTX.

would also be nice to have the ability to change the label sizes.

thanks for the development btw, I always wanted to be able to have GIFs and telemetry on my kraken!

**Comment by brunoandradebr** [comment]
Thank you my friend I really appreciate this. I will fix it soon. I'm away from my country, I will back next week then I fix it. Your issue helps improve it.

**Comment by brunoandradebr** [comment]
@V333Y  I've fixed AMD gpu labels! can check if it's ok now ?  Label size I can't do it now but I've added to backlog.

**Comment by V333Y** [comment]
@brunoandradebr 
![unnamed](https://github.com/brunoandradebr/nzxt/assets/173413820/7be07490-9b60-41a2-a5fb-89ef8a111d33)
works perfect. YOU ARE A G!
