### ISSUE TITLE
Tem como adicionar mais círculos para configurar mais cores?

### ISSUE THREAD

**Issue by GabrielQueiroz-br** [brunoandradebr/nzxt#14]
Bom dia, Bruno! Primeiramente gostaria de agradecer pelo compartilhamento da integração. Sou muito leigo no assunto e gostaria de saber se é possível adicionar mais círculos de cores no monitoramento, semelhante ao que acontece no efeito spectrum wave da NZXT e caso seja possível, tem como fazer com que eles girem igual às ventoinhas? Agradeço desde já.
![Captura de tela 2024-06-30 144322](https://github.com/brunoandradebr/nzxt/assets/174269887/84d18ac5-927a-4e55-8387-5ca00477730d)

**Comment by brunoandradebr** [comment]
Opa, vlw demais, @GabrielQueiroz-br! Infelizmente não rola de implementar isso na integração que fiz.
