### ISSUE TITLE
Wrong Gpu listed

### ISSUE THREAD

**Issue by Code-Xer0** [brunoandradebr/nzxt#16]
I have a dock connected to my machine and its pulling that for the gpu info (Dell Display Link USB Device) Instead of my 2070 Super

**Comment by brunoandradebr** [comment]
@Code-Xer0  humm I will try a fix. latter you can check.

**Comment by brunoandradebr** [comment]
@Code-Xer0  Can you please tell me if it's working properly ? If don't, please send me a picture of what is showing in your pump screen. It must be showing this version in your configuration screen: 

<img width="155" alt="image" src="https://github.com/user-attachments/assets/b6fad158-d5a7-465f-8410-92c223ecadb0">

**Comment by Code-Xer0** [comment]
Works as intended thanks boss!
