### ISSUE TITLE
Broken integration

### ISSUE THREAD

**Issue by Sidepie** [brunoandradebr/nzxt#17]
Hi,
Integration is realized via a redirect using acobaia.io but that domain is now unavailable.

**Comment by brunoandradebr** [comment]
Hi. yep I'm trying to connect my domain to my github =( and by acident I broke url. it's a cache, it will come back soon. BUT if you don't wanna wait nzxt update cache, just change url integration to this https://brunoandradebr.github.io/nzxt/?t=1     <- this ?t=1 will force refresh bump's cache.

**Comment by Sidepie** [comment]
Yes, you're right, it's working now. Thanks! :)
