### ISSUE TITLE
Enhancement/Suggestion

### ISSUE THREAD

**Issue by Psykrot** [brunoandradebr/nzxt#18]
1. Allow creation (and renaming) of more profile themes:
![image](https://github.com/user-attachments/assets/4bbc018c-eaf3-48bc-b5fb-ff8a8f4d27e0)

2. Add some sort of support for swapping between themes via webhooks.

**Comment by brunoandradebr** [comment]
1 - I will think about this. a way to export and load from file.

2 - Can you elaborate better ?

**Comment by Psykrot** [comment]
The webhook idea is based off of the previous support for external control that was removed when accounts went away. You used to be able to set up an IFTTT applet that would take a webhook and trigger a profile change in the CAM software. You could use this to externally control what was displayed on the Kraken screen by setting up different CAM profiles and swapping between them through thosw webhooks.

Since your integration has the ability to swap between its own profile themes in the dropdown pictured above,  I figured something similar could be achieved if webhook support was added.

Essentially, each theme would have its own webhook URL that listens for the webhook, so when I send the webhook from an external source (like my Stream Deck), the theme is swapped and the Kraken display updates without having to open the CAM software.

The first suggestion is kinda related to the webhooks though. Since I would be relying on each theme to have its own webhook URL, adding more than 4 profiles would allow for more themes to custimize and swap between.

Hopefully that makes sense, let me know if not.

**Comment by brunoandradebr** [comment]
Got it! It would be nice feature, depending on what application you open it changes theme to it's style. But If I'm not wrong nzxt api needs to provide their api with webooks and I think it dosn't. I'm searching for webhooks to understand it better. thanks btw.

**Comment by Psykrot** [comment]
I got a notification that this was completed and went to check it out, but didn't see anything different in the web configuration page. Were there limitations to the original suggestion(s)?

**Comment by brunoandradebr** [comment]
Sorry for late return. As I said, I think that nzxt must implement a web hook to be possible to do this, if I didnt get it wrong, it's not possible in web integration.
