### ISSUE TITLE
Multigpu selection. Wrong Gpu. 

### ISSUE THREAD

**Issue by Code-Xer0** [brunoandradebr/nzxt#19]
Selecting Displaylink USB hub as primary in infographic. 
![20241108_114922](https://github.com/user-attachments/assets/89f1199e-9561-44e5-b625-25406633d284)

**Comment by brunoandradebr** [comment]
Thanks for your print! I'm away from home today, Sunday I will be patching a fix update for your case!

**Comment by brunoandradebr** [comment]
Is it the same Dell display hub ? I'm writing a fix right now.

**Comment by brunoandradebr** [comment]
Can you check if it's working ? It's supposed to show in header v1.6.3 if don't  use this url to force cache update: https://acobaia.io/nzxt

**Comment by Code-Xer0** [comment]
Works Great Appreciate you boss!
