### ISSUE TITLE
GPU detection priority changed

### ISSUE THREAD

**Issue by alexissorokine** [brunoandradebr/nzxt#2]
As of the last update, the interface no longer shows my RTX 3090 as the GPU. It instead shows the integrated graphics of my Intel CPU.
Would it be possible to change the GPU detection priority, or to give the user an option to choose which GPU to display?

I see that another identical issue was marked as closed, however the issue still persists.

**Comment by brunoandradebr** [comment]
> I see that another identical issue was marked as closed, however the issue still persists.

yeah, I thought I fixed by getting a different gpu array index but crashad for you lol

nzxt api to get gpu do not give you a pattern for main gpu =(

I'm working on a fix, thanks for your feedback

**Comment by brunoandradebr** [comment]
@alexissorokine I've updated. Can you check if it's working now ? and thanks for PR appreciated it

**Comment by alexissorokine** [comment]
It's working for me now :)
I'm closing the issue.
