### ISSUE TITLE
9800x3D is not recognized

### ISSUE THREAD

**Issue by dudeyourajerk** [brunoandradebr/nzxt#20]

**Comment by brunoandradebr** [comment]
Can  you provide a photo what is showing in your display ?

**Comment by dudeyourajerk** [comment]
![IMG_3836](https://github.com/user-attachments/assets/00a18855-546a-4fca-be91-800aba146872)

**Comment by brunoandradebr** [comment]
Can you please tell me what information is showing in your nzxt devices panel ? 

like mine: 
![image](https://github.com/user-attachments/assets/153e93bd-cc76-4e92-9348-1bbb43fdfd0b)

**Comment by brunoandradebr** [comment]
I have just googled and sounds like your processor is having some trouble with nzxt: 

https://www.reddit.com/r/NZXT/comments/1gral2l/9800x3d_not_recognized_by_cam/

maybe a future update gonna fix it.
