### ISSUE TITLE
Graph is frozen after PC wake-up

### ISSUE THREAD

**Issue by TheGITofTeo997** [brunoandradebr/nzxt#6]
Hello,
I honestly don't know if this is an issue from NZXT Cam Web Integration itself, or just in this particular project. What simply happens is that when you wake-up your computer from Windows Sleep mode, the graph is completely frozen at the moment you put your computer to sleep. The only way to make it responsive again is either to close-reopen NZXT Cam or simply swap what you have on the Kraken LCD with something else and then put this graph back.

Would this be fixable in anyway in case it does not depend from Cam?

**Comment by brunoandradebr** [comment]
humm It sounds like a CAM bug, web integration can't handle this kind of behavior. Does it happens with non web integration as well ? Now I'm curious, I will turn on sleep mode to check if happens with me. but it would be better to open this issue at nzxt docs as well : https://github.com/NZXTCorp/web-integrations-docs/issues.

**Comment by brunoandradebr** [comment]
I tested entering sleep mode and hibernate mode and in both case they back normally from frozen state. maybe something with your device config or windows.

**Comment by TheGITofTeo997** [comment]
> humm It sounds like a CAM bug, web integration can't handle this kind of behavior. Does it happens with non web integration as well ? Now I'm curious, I will turn on sleep mode to check if happens with me. but it would be better to open this issue at nzxt docs as well : https://github.com/NZXTCorp/web-integrations-docs/issues.

Thank you so much for the answer and since I haven't told already, thanks for sharing this awesome project. Before using this I was simply using the Dual Infograph with some customized colors I put, but the config was the one directly from NZXT Cam Dual Infograph. That one has always worked, I put my computer everyday to sleep and then get back and never got this issue. 
Unfortunately this does seem to happen with this Web Integration. Even if it was my config, thing that it's probably true, I wouldn't honestly know what to touch. As I stated the only way to get it back for me after sleep mode is to put on another config (i.e. Dual Infograph) and then get back to this Web integration.

Shall I notice NZXT about this?

**Comment by brunoandradebr** [comment]
Thanks, I appreciate it. for not getting this error even entering these mods, it's hard to tell the origin, but it would be greate to have nzxt developers consideration, so openning an issue there would be better. I'll be watching the issue to be informed.

**Comment by TheGITofTeo997** [comment]
Hello, I've opened an issue here https://github.com/NZXTCorp/web-integrations-docs/issues/13

**Comment by TheGITofTeo997** [comment]
@brunoandradebr has this integration been updated in the meantime? Because it looks like the sleep issue might be fixed!

**Comment by brunoandradebr** [comment]
@TheGITofTeo997 yeah, I have updated with more custom things but nothing related to the bug you mentioned =s. But in the meantime nzxt realsed an update. We will never know hahahaha

**Comment by brunoandradebr** [comment]
But, reinforcing... this bug never happened to me and I think to anyone else =s

**Comment by TheGITofTeo997** [comment]
> @TheGITofTeo997 yeah, I have updated with more custom things but nothing related to the bug you mentioned =s. But in the meantime nzxt realsed an update. We will never know hahahaha

Yeah I just realized that. I noticed there were also NZXT updates, I will observe the behaviour in the next days and if it still works I will close the issue

**Comment by TheGITofTeo997** [comment]
I've tested multiple times and either NZXT has been updated or this integration has been updated too, but for now this is fixed for me. I will close the issue!
