### ISSUE TITLE
Won't allow PC to sleep or PC Monitor to shut off

### ISSUE THREAD

**Issue by chrisdodgson** [brunoandradebr/nzxt#7]
When I have this enabled it will not let me screen shut off or my PC to go to sleep. This is by far the best NZXT screen so I hope this gets fixed soon. If I enable this wen integration and run "powercfg -requests" it shows NZXT Cam as Video Wake Lock. If I remove the integration and run the script NZXT Cam allows the screen to shut off.

**Comment by brunoandradebr** [comment]
Hi there, Chris. This kind of "issue" is out of my hand. My integration is just a web app, I can't reach the environment where my web app runs. It would be better to open this issue on nzxt repository cause I can't touch this kind of problem. Appreciate you liked the integration and sorry for not helping fixing this. An issue similar to that was open: https://github.com/brunoandradebr/nzxt/issues/6

**Comment by brunoandradebr** [comment]
An issue similar to that was open: https://github.com/brunoandradebr/nzxt/issues/6

**Comment by brunoandradebr** [comment]
I'll be closing for not been integration issue.
