### ISSUE TITLE
Font change

### ISSUE THREAD

**Issue by drxnaren** [brunoandradebr/nzxt#9]
Is there any way to change the font to something else? I currently see 4 fonts (Segoe UI, Staatliches, DotGothic16 and Pixelify Sans). I want to add more fonts to this list.

**Comment by brunoandradebr** [comment]
humm it's not possible to upload new fonts right now and I think it will not be any possible. but I will give a try. do you have any font suggestions to include ?

**Comment by drxnaren** [comment]
I was looking for an alternative pixel font, since i think the numbers on Pixelify Sans look weird, especially the 2's and 5's. I found Minecraft to be a good one.

Edit: Here's a link (https://www.dafont.com/minecraft.font)

**Comment by brunoandradebr** [comment]
nice! I'll be adding minecraft soon. maybe today latter.

**Comment by brunoandradebr** [comment]
I've added Minecraft font try reload url inside nzxt app to update with new font. Gif service is out temporarily =(

**Comment by drxnaren** [comment]
It works, and looks great. Nice work on the quick actions! :)

**Comment by brunoandradebr** [comment]
Giphy service is back! i'm closing this issue. thanks for your feedback. if you share your setup please tag me on instagram https://www.instagram.com/brunoandradebr/
